apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue-service
  template:
    metadata:
      labels:
        app: queue-service
    spec:
      containers:
        - name: queue-service
          image: snesh111/queue-service
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: queue-service
spec:
  selector:
    app: queue-service
  ports:
    - port: 3000
      targetPort: 3000